Applied a new flag to jxl-perfhistory

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -268,7 +268,7 @@ jobs:
       continue-on-error: true  # Never fail the PR
       run: |
         mkdir -p benchmark-binaries
-        (jxl-perfhistory -r 5 -b benchmark-binaries -g "testimages/*.jxl" -c 0.99 -e 0.03 --ignore-noisy-system || echo "Benchmark failed") > benchmark.txt
+        (jxl-perfhistory -r 5 -b benchmark-binaries -g "testimages/*.jxl" -c 0.99 -e 0.03 --ignore-noisy-system --pr-comment || echo "Benchmark failed") > benchmark.txt
 
     - name: Save PR context
       run: |
